package com.ecom.tests.model.onboarding;

public record MerchantData(
    String merchantID,
    String terminalID,
    String accountLogin,
    String reqMerchantID,
    String mcc,
    String reqTerminalID,
    String country,
    String city,
    String street,
    String name,
    String bankCode,
    String currency,
    String siteUrl,
    String phone,
    String contact,
    String fax,
    String email,
    String zip,
    String remark,
    String notifyUrl,
    String successUrl,
    String failureUrl,
    String closedayHour,
    String ipn,
    String terminalTypeId,
    String identification,
    String timeZone,
    String sms,
    String viber,
    String facebook) {}
